### ISSUE TITLE
Replit removed pinging services

### ISSUE THREAD

**Issue by krishnakpanyala** [VulcanWM/WeGreek#1]
Replit removed the pinging services and this website is unavailable. How to open 😭😭😭??

**Comment by VulcanWM** [comment]
Replit removed free hosting altogether, and nobody really uses this website so I'm not hosting it elsewhere.
Basically you can't view it anymore.
Why did you want to see it anyways lmao?

**Comment by krishnakpanyala** [comment]
The nostalgia 🤩

I mean irdk i just remembered that website existed.
